name: build--macos-x86_64

on: [ push, pull_request ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  macos-x86_64:
    if: 1
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare build environment
        run: |
          env
          echo $HOME

          brew config

          brew install  wget curl  libtool automake  re2c llvm flex bison
          
          ls -lh $(xcrun --show-sdk-path)
          
          ifconfig

          CURRENT_USER=$(whoami)
          echo ${CURRENT_USER}

      - name: production artifacts
        if: 0
        uses: actions/upload-artifact@v3
        with:
          name: macos-ffmpeg
          path: ./ffmpeg

      - name: gh release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./ffmpeg
          draft: true
          prerelease: true
